# Services definition for building & deploying

services:

  app:
    # Build
    image: ${IMAGES_PREFIX:-app}:${IMAGES_TAG:-latest}
    build:
      context: ./app
      dockerfile: ./Dockerfile
      target: app_prod
