enum ListenerTypes
{
    CHANNEL_MESSAGE = 'CHANNEL_MESSAGE',
    MESSAGE = 'MESSAGE',
    MESSAGE_COMPONENT = 'MESSAGE_COMPONENT',
    MESSAGE_REACTION = 'MESSAGE_REACTION',
}

export default ListenerTypes
