name: Publish npm package

on:
  # Triggers the workflow on published releases
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish npm package

    # Runs on Ubuntu
    runs-on: ubuntu-latest

    # Permissions
    permissions:
      packages: write
      contents: read

    # Maximum run time in minutes before the job is canceled
    timeout-minutes: 10

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE
      - name: Checkout the project
        uses: actions/checkout@v2

      # Setup to publish to npm
      - name: Install Node.js v16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Check Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Clean install the project
        run: npm clean-install

      - name: Publish the project
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # # Setup to publish to GitHub Packages
      # - name: Log in to GitHub npm Registry
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '12.x'
      #     registry-url: 'https://npm.pkg.github.com'
      #     scope: '@matiboux'

      # - run: npm clean-install

      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
