name: Publish npm package

on:
  # Triggers the workflow on push or pull request events for the default branch
  push:
    branches: [ master ]

jobs:
  publish:
    name: Publish Docker image

    # Runs on Ubuntu
    runs-on: ubuntu-latest

    # Permissions
    permissions:
      packages: write
      contents: read

    # Maximum run time in minutes before the job is canceled
    timeout-minutes: 10

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Log in to GitHub npm Registry
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - run: npm install

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
